//origin='http://jroller.com/francoisledroff/entry/java_plus_rapide_plus_l%C3%A9ger'
origin='http://www.jroller.com/francoisledroff/entry/apache_on_ssl_as_a1'
//'''http://www.jroller.com/francoisledroff/entry/javapolis_2004'
jbake_output='/Users/ledroff/workspace/github/blog/src/jbake/content'
author='Francois Le Droff'
